export interface Product {
  id: number;
  name: string;
  sku: string;
  image: string;
  category: string;
}

export const productsData: Product[] = [
  {
    id: 1,
    name: "UPS ESOL TRI PT 10KVA Pantalla Touch Full Color",
    sku: "UPSESESOLTRIPT10CB",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPSESESOLTRIPT30SB-300x300.jpg",
    category: "ups-trifasicas",
  },
  {
    id: 2,
    name: "Banco de Baterías ESOL TRI PT 80X9ah",
    sku: "BPESOLTRIPTS/B",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/EnerSafe-Banco-de-Baterias-1-300x300.png",
    category: "ups-trifasicas",
  },
  {
    id: 3,
    name: "Modulo UPS Modular 20kW",
    sku: "MODSAFE20PM",
    image: "https://enersafelatam.com/wp-content/uploads/2023/12/Enersafe80-300x300.jpg",
    category: "ups-modulares",
  },
  {
    id: 4,
    name: "Frame UPS Modular Hasta 200kW",
    sku: "MODSAFE1020KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/ENERSAFE-60-scaled-1-300x300.jpg",
    category: "ups-modulares",
  },
  {
    id: 5,
    name: "Frame UPS Modular Hasta 60kW",
    sku: "MODSAFE520KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/ENERSAFE-60-scaled-1-300x300.jpg",
    category: "ups-modulares",
  },
  {
    id: 6,
    name: "UPS ESOL RTH 1KVA 36vdc",
    sku: "UPSESESOLRTH1KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-300x300.jpg",
    category: "ups-online",
  },
  {
    id: 7,
    name: "UPS ESOL T-E 1Kva/900Watts",
    sku: "UPSEOLTE1KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPS-online-Esol-TE--300x300.jpg",
    category: "ups-online",
  },
  {
    id: 8,
    name: "UPS ESIT 600Va/360Watts",
    sku: "UPSESESIT600VA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPS-interactiva-Esit-600va-2-300x300.jpg",
    category: "ups-interactivas",
  },
  {
    id: 9,
    name: "UPS ESOL RTH-C 2Kva 48vdc",
    sku: "UPSESOLRT48V2K",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-300x300.jpg",
    category: "ups-online",
  },
  {
    id: 10,
    name: "UPS ESOL RTH 2Kva 72vdc",
    sku: "UPSESESOLRTHC2KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-300x300.jpg",
    category: "ups-online",
  },
  {
    id: 11,
    name: "UPS ESOL T-E 10Kva/10000Watts",
    sku: "UPSOLTE10KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe60-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 12,
    name: "UPS ESOL T-E 6Kva/6000Watts",
    sku: "UPSOLTE6KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe60-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 13,
    name: "Tarjeta SNMP UPS Trifásica",
    sku: "UPSSNMPCARDS1",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Enersafe5-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 14,
    name: "UPS ESOL RTH-C 1Kva 24vdc",
    sku: "UPSESOLRTHC1KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 15,
    name: "UPS ESOL RTH 3Kva 72vdc",
    sku: "UPSESESOLRTHC3KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 16,
    name: "UPS ESOL RTH-C 3Kva 120V",
    sku: "UPSESOLRTHC3KVA120VAC",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 17,
    name: "UPS RTH-C PRO 10Kva/10kW",
    sku: "UPSBATRT10KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2025/04/1-RTHC6KVA-con-sombra-300x300.jpg",
    category: "ups-online",
  },
  {
    id: 18,
    name: "UPS RTH-C PRO 6Kva/6kW",
    sku: "UPSBATRT6KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2025/04/1-RTHC6KVA-con-sombra-300x300.jpg",
    category: "ups-online",
  },
  {
    id: 19,
    name: "UPS ESOL RTH Long Run 10Kva/9000Watts Sin baterías",
    sku: "UPSESOLRTHCLR10KVA_",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 20,
    name: "UPS ESOL RTH Long Run 6Kva/5400Watts Sin baterías",
    sku: "UPSESOLRTCLR6KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-300x300.jpg",
    category: "ups-online",
  },
  {
    id: 21,
    name: "UPS ESOL RTH-C Long Run 1Kva/900Watts 24vdc Sin baterías",
    sku: "UPSESOLRTHCLR1KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 22,
    name: "UPS ESOL RTH-C Long Run 3Kva/2700Watts 72vdc Sin baterías",
    sku: "UPSESOLRTHCLR3KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 23,
    name: "Batería Enersafe 12V/33Ah",
    sku: "BATENER12V33AH",
    image: "https://enersafelatam.com/wp-content/uploads/2024/03/12V-33Ah-300x300.png",
    category: "baterias",
  },
  {
    id: 24,
    name: "Batería Enersafe 12V/40Ah",
    sku: "BATENER12V40AH",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Imagen-sin-fondo-1-300x300.png",
    category: "baterias",
  },
  {
    id: 25,
    name: "Batería Enersafe 12V/55Ah",
    sku: "BATENER12V55AH",
    image: "https://enersafelatam.com/wp-content/uploads/2023/10/E-HR-HR12-200W-55AH-300x300.png",
    category: "baterias",
  },
  {
    id: 26,
    name: "Batería ENERSAFE 12V/100Ah",
    sku: "BATENER12V100AH",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Imagen-sin-fondo-300x300.png",
    category: "baterias",
  },
  {
    id: 27,
    name: "Banco de Baterías ESOL RTH- 1Kva",
    sku: "BPESOLRTH-1KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Enersafe81_logo-nuevo-300x300.jpg",
    category: "baterias",
  },
  {
    id: 28,
    name: "Banco de Baterías ESOL RTH 2-3 kva",
    sku: "BPESOLRT2/3KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Enersafe81_logo-nuevo-300x300.jpg",
    category: "baterias",
  },
  {
    id: 29,
    name: "Kit Rieles ESOL RTH",
    sku: "ACCESRIELESOL",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Enersafe19-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 30,
    name: "Batería Enersafe 12V/5Ah",
    sku: "BATENER12V5AH",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/12V-5aH-300x300.png",
    category: "baterias",
  },
  {
    id: 31,
    name: "Batería Enersafe 12V/7Ah",
    sku: "BATENER12V7AH",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/17V-7Ah-300x300.png",
    category: "baterias",
  },
  {
    id: 32,
    name: "Baterías Enersafe 12V 9AH",
    sku: "BATENER12V9AH",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/12V-9Ah-300x300.png",
    category: "baterias",
  },
  {
    id: 33,
    name: "Batería Enersafe 12V/18Ah",
    sku: "BATENER12V18AH",
    image: "https://enersafelatam.com/wp-content/uploads/2025/01/Imagen-de-WhatsApp-2025-01-07-a-las-17.23.18_d1a64259-300x300.jpg",
    category: "baterias",
  },
  {
    id: 34,
    name: "Batería Enersafe 12V/26Ah",
    sku: "BATENER12V26AH",
    image: "https://enersafelatam.com/wp-content/uploads/2025/01/Bateria-12-26-300x300.jpg",
    category: "baterias",
  },
  {
    id: 35,
    name: "Tarjeta SNMP UPS DS806 USB",
    sku: "SNMPMTMINI",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Enersafe3-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 36,
    name: "Tarjeta SNMP UPS DS801 SIN USB",
    sku: "SNMPMINIUSB",
    image: "https://enersafelatam.com/wp-content/uploads/2025/01/1-SNMP-MONOFASICA-VIOLETA-801-CON-SOMBRA-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 37,
    name: "UPS ESOL RTH-L 1KVA, Batería Ion Litio",
    sku: "UPSESESOLRTHL1KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 38,
    name: "UPS ESOL RTH-L 2KVA, Batería Ion Litio",
    sku: "UPSESESOLRTHL2KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 39,
    name: "UPS ESOL RTH-L 3KVA, Batería Ion Litio",
    sku: "UPSESESOLRTHL3KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe42-768x768.jpg",
    category: "ups-online",
  },
  {
    id: 40,
    name: "UPS ESOL T-E 2Kva/1800Watts",
    sku: "UPSESOLTE2KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPS-online-Esol-TE--300x300.jpg",
    category: "ups-online",
  },
  {
    id: 41,
    name: "UPS ESOL T-E 3Kva/2700Watts",
    sku: "UPSESOLTE3KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPS-online-Esol-TE--300x300.jpg",
    category: "ups-online",
  },
  {
    id: 42,
    name: "Banco de Batería TRIRT20KVA 40 Baterías 12V9Ah",
    sku: "BPEESOLTRIRT240",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/EnerSafe-Banco-de-Baterias-1-300x300.png",
    category: "baterias",
  },
  {
    id: 43,
    name: "UPS ESIT 1000Va/600Watts",
    sku: "UPSIMICRO1000",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPS-interactiva-Esit-1000va-2-300x300.jpg",
    category: "ups-interactivas",
  },
  {
    id: 44,
    name: "UPS ESIT 2000Va/1200Watts",
    sku: "UPSIMICRO2000",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPS-interactiva-Esit-2000va-2-300x300.jpg",
    category: "ups-interactivas",
  },
  {
    id: 45,
    name: "UPS Modular SubRack",
    sku: "UPSMODSUBR80G",
    image: "https://enersafelatam.com/wp-content/uploads/2023/07/Enersafe78-300x300.jpg",
    category: "ups-modulares",
  },
  {
    id: 46,
    name: "UPS ESOL TRI PT 20KVA Pantalla Touch Full Color",
    sku: "UPSESESOLTRIPT20CB",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPSESESOLTRIPT30SB-768x768.jpg",
    category: "ups-trifasicas",
  },
  {
    id: 47,
    name: "UPS ESOL TRI PT 30KVA Pantalla Touch Full Color",
    sku: "UPSESESOLTRIPT30CB",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPSESESOLTRIPT30SB-768x768.jpg",
    category: "ups-trifasicas",
  },
  {
    id: 48,
    name: "UPS ESOL TRI PT 40KVA Pantalla Touch Full Color",
    sku: "UPSESOLTRIPT40CB",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPSESESOLTRIPT30SB-768x768.jpg",
    category: "ups-trifasicas",
  },
  {
    id: 49,
    name: "UPS TRI PT 60KVA BAT/INT Pantalla Touch Full Color",
    sku: "UPSTRIPT60KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/UPS-TRIFASICA-60KVA-SIN-FONDO-300x300.png",
    category: "ups-trifasicas",
  },
  {
    id: 50,
    name: "UPS TRI PT 100KVA BAT/INT Pantalla Touch Full Color",
    sku: "UPSTRIPT2100KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Imagen-UPS-60-100KVA-EnerSafe-300x300.png",
    category: "ups-trifasicas",
  },
  {
    id: 51,
    name: "UPS TRIMONO ESOL RTH 6 KVA 3:1",
    sku: "UPSESOL3-1-6KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe58-300x300.jpg",
    category: "ups-online",
  },
  {
    id: 52,
    name: "UPS ESOL TRI RT 20KVA Rackeable",
    sku: "UPSESOLTRIRT20KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/3-UPS-RT20KVA-con-sombra-300x300.jpg",
    category: "ups-trifasicas",
  },
  {
    id: 53,
    name: "UPS TRIMONO ESOL RTH 10 KVA 3:1",
    sku: "UPSESOLRTH3-1-10KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe58-300x300.jpg",
    category: "ups-online",
  },
  {
    id: 54,
    name: "Tablero Bypass 10-40kva Trifasico",
    sku: "BYPASSTRI10-40KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/BYPASS-TRIFASICO-con-sombra-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 55,
    name: "Inversor Cargador 2400VA/1440W 24VDC",
    sku: "INVCAR1440",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe15-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 56,
    name: "Inversor Cargador 1500VA/900W 12VDC",
    sku: "INVCAR900",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe15-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 57,
    name: "Modulo Distribucion Bypass Rackeable 20 kva rt",
    sku: "MDESOLTRIRT20KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/Enersafe25-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 58,
    name: "Bypass PDU Rackeable 6/10kva monofasico",
    sku: "BYPPRDPDU610KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2025/09/2-PDU-con-sombra-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 59,
    name: "Bypass Paralelismo Rackeable 6/10kva monofasico",
    sku: "BYPRAPROPDU610KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2024/02/2-PDU-PARALELISMO-con-sombra-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 60,
    name: "Switch Bypass con PDU 1-3Kva",
    sku: "RT9100-PDU",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Enersafe21-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 61,
    name: "Tarjeta SNMP UPS Monofasica",
    sku: "SNMP-ESOL-KVA",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Enersafe1-300x300.jpg",
    category: "accesorios",
  },
  {
    id: 62,
    name: "Tarjeta SNMP ATS",
    sku: "SNMPATS",
    image: "https://enersafelatam.com/wp-content/uploads/2023/06/Enersafe9-300x300.jpg",
    category: "accesorios",
  },
];

export const dynamic = 'force-dynamic';

export async function generateStaticParams() {
  return productsData.map((product) => ({
    category: product.category,
  }));
}